### ISSUE TITLE
Create a hotsite for the Schedule

### ISSUE THREAD

**Issue by luanfonceca** [luanfonceca/speakerfight#227]
Today we can embedded it into a full site just by using his iframe, it should be nice if we have a auto generated page for this event.

If the schedule was generated we can access this hotsite in the `/events/<event_sug>/schedule/`, but we also need to differentiate that call from the call that the iframe does, in order to not broke the embedded.

**Comment by luanfonceca** [comment]
This Hotsite should be a standalone Event app. It should be implemented as a Progressive Web App.

When the users install it they will be allowed to Receive Notifications about the next activities like Coffeebreak, Keynote talks and other stuff like that.

**Comment by arturfelipe** [comment]
Hi @luanfonceca can I work with this one? I'm really interested in PWAs and want to have an opportunity to apply the techniques to a production project.

**Comment by luanfonceca** [comment]
Sure you can take this!

<3

**Comment by thulioph** [comment]
Hey guys, after discussing with @luanfonceca, I think that the next steps to do this issues are:

## Roadmap

- [ ] Add the social meta-tags to share the event schedule. (Twitter, Facebook and Google Plus)

- [ ] Add `SASS` to the project.

- [ ] Remove the `jQuery` and use the vanilla javascript to make the "hard work".

- [ ] Save the event schedule on the Home Screen. - **WebApp**

- [ ] Send notifications to remember the next talk. - **WebApp**

- [ ] Allow the schedule to works offline. - **WebApp**

What do you think about?

Thanks.

**Comment by arturfelipe** [comment]
Good @thulioph ! I'm currently working with the 2 last items. The "Save the event schedule on the Home Screen" we need to decide what to consider an app. 

* Will the entire app be only the Schedule page? 
* Or the entire site?

One thing to get in mind is, when the users add the page (app) to the home screen it will never again apply changes in the `manifest.json` file. Only if the users remove it and add it again. So we need to be sure about the information in the manifest:

https://developer.mozilla.org/en-US/docs/Web/Manifest

Do you get it?

Do we go this way:

https://speakerfight.com/manifest.json
```json
{
  "name": "Speakerfight",
  "short_name": "Speakerfight",
  "start_url": ".",
}
```

or this?
https://speakerfight.com/events/rupy-natal/schedule/manifest.json
```json
{
  "name": "Speakerfight Schedule",
  "short_name": "SpeakerfightSchedule",
  "start_url": ".",
}
```

@thulioph would you like to work with the 3 first tasks? I can help with that either.

Thanks.

**Comment by thulioph** [comment]
Hey @arturfelipe, great!

I think that the purpose is only the schedule page because when the event shares your own `schedule` page, it's related to the event, not the entire app. IMHO, the second approach using the `event-slug/manifest.json` make more sense.

I already started the implementation of these 3 last tasks, If you need a hand, I'm here!

What do you think @luanfonceca ?
